In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [7]:
a[2]

3

In [8]:
type(a[0])

numpy.int32

In [12]:
b = np.array([1,2,3],dtype=float)

In [13]:
b

array([1., 2., 3.])

In [16]:
string = np.array([1,2,3],dtype = str)

In [17]:
string

array(['1', '2', '3'], dtype='<U1')

In [18]:
str_1 = np.array([1888,24,366],dtype = str)

In [20]:
str_1

array(['1888', '24', '366'], dtype='<U4')

In [21]:
np.zeros(2)

array([0., 0.])

In [26]:
zeros = np.zeros(20,dtype = int)

In [28]:
print(zeros)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [29]:
np.ones(4)

array([1., 1., 1., 1.])

In [30]:
#now I want to have 3's in an array
#it may contain 0's 1's or any other value..
#how to do it
3*np.ones(5)

array([3., 3., 3., 3., 3.])

In [32]:
x = np.empty(6)
x.fill(3)
print(x)

[3. 3. 3. 3. 3. 3.]


In [36]:
y = np.arange(8)
y

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
x = np.arange(2,30,5)
x

array([ 2,  7, 12, 17, 22, 27])

In [53]:
a=([1,2,3,4])

In [54]:
a

[1, 2, 3, 4]

In [57]:
b = ([9,10,11,12])
np.concatenate((a,b),axis=0)

array([ 1,  2,  3,  4,  9, 10, 11, 12])