In [1]:
import numpy as np

In [8]:
np.random.randint(100)

63

In [56]:
np.random.randint(3)

1

In [26]:
np.random.rand(2)

array([0.37715817, 0.89424787])

In [28]:
np.random.rand(8,4)

array([[0.44173262, 0.67086466, 0.70034026, 0.36410986],
       [0.8788408 , 0.83637948, 0.73507619, 0.63511757],
       [0.77255452, 0.92549672, 0.31171454, 0.36049564],
       [0.21387092, 0.2410111 , 0.6415315 , 0.99526454],
       [0.14409882, 0.94225189, 0.87629066, 0.18868632],
       [0.63724313, 0.69129967, 0.23580673, 0.92797583],
       [0.68738737, 0.82617048, 0.29966031, 0.07551053],
       [0.25961527, 0.26151754, 0.33165772, 0.07693252]])

In [70]:
np.random.random(4)

array([0.88635077, 0.41983161, 0.88424767, 0.77707989])

In [72]:
b = np.array([1,2,3,4,5,6,7,8,9,2,3,4,5,6,7,8,2,2,2,24,4,4,11,7,99,9,9,4,4,4])

In [73]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  2,  3,  4,  5,  6,  7,  8,  2,
        2,  2, 24,  4,  4, 11,  7, 99,  9,  9,  4,  4,  4])

In [75]:
b_unique = np.unique(b)
print(b_unique)

[ 1  2  3  4  5  6  7  8  9 11 24 99]


In [91]:
b.reshape(3,10)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  2],
       [ 3,  4,  5,  6,  7,  8,  2,  2,  2, 24],
       [ 4,  4, 11,  7, 99,  9,  9,  4,  4,  4]])

In [93]:
b.transpose()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  2,  3,  4,  5,  6,  7,  8,  2,
        2,  2, 24,  4,  4, 11,  7, 99,  9,  9,  4,  4,  4])

In [96]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [100]:
rev_arr = np.flip(arr)
rev_arr

array([7, 6, 5, 4, 3, 2, 1])